# Generated by Django 4.0 on 2022-01-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='template',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
