# Generated by Django 4.0 on 2022-01-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_template_project_link_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
