# Generated by Django 4.0.1 on 2022-08-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_tag_slug_alter_tag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
