# Generated by Django 4.0.1 on 2022-08-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_tag_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(default='', max_length=50),
        ),
    ]
