# Generated by Django 4.0.1 on 2022-08-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_blog_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=50)),
                ('link_desc', models.CharField(max_length=100)),
                ('link_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(to='portfolio.Link'),
        ),
    ]
