# Generated by Django 4.0.1 on 2022-09-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_link_remove_project_link_project_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=50)),
                ('link_url', models.URLField(max_length=500)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
