# Generated by Django 4.0.1 on 2022-09-15 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_imagelinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageLinks',
            new_name='ImageLink',
        ),
    ]
