# Generated by Django 4.0.1 on 2022-09-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_imagelinks_imagelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelink',
            name='link_url',
        ),
        migrations.AddField(
            model_name='imagelink',
            name='goole_drive_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
