# Generated by Django 4.0.1 on 2022-09-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_imagelink_link_url_imagelink_goole_drive_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelink',
            old_name='goole_drive_code',
            new_name='google_drive_code',
        ),
    ]
