# Generated by Django 4.0.1 on 2022-09-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_rename_goole_drive_code_imagelink_google_drive_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10, null=True)),
                ('job_description', models.CharField(max_length=100)),
            ],
        ),
    ]
