# Generated by Django 5.1.15 on 2026-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_experience_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.CharField(help_text='Short update, e.g. "Paper accepted at ICLR 2024."', max_length=400)),
                ('url', models.URLField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Divij Handa', max_length=80)),
                ('role', models.CharField(default='LLM Researcher', help_text='Short role/title shown under your name, e.g. "LLM Researcher".', max_length=120)),
                ('tagline', models.CharField(blank=True, help_text='One-line hook streamed in the hero, e.g. your research focus.', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='A few sentences about you for the About section.', max_length=1500)),
                ('location', models.CharField(blank=True, default='Tempe, Arizona', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('resume', models.FileField(blank=True, help_text='Upload your CV/resume PDF here — the download button uses it.', null=True, upload_to='resume/')),
                ('github_url', models.URLField(blank=True, max_length=300)),
                ('linkedin_url', models.URLField(blank=True, max_length=300)),
                ('scholar_url', models.URLField(blank=True, max_length=300, verbose_name='Google Scholar URL')),
                ('twitter_url', models.URLField(blank=True, max_length=300, verbose_name='X / Twitter URL')),
                ('huggingface_url', models.URLField(blank=True, max_length=300, verbose_name='Hugging Face URL')),
                ('orcid_url', models.URLField(blank=True, max_length=300, verbose_name='ORCID URL')),
                ('instagram_url', models.URLField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(help_text='One-line description.', max_length=300)),
                ('description', models.TextField(blank=True, max_length=1200)),
                ('icon', models.CharField(blank=True, default='', help_text='Optional emoji shown with the area, e.g. 🧠.', max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('event', models.CharField(blank=True, help_text='Venue / course / committee.', max_length=200)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('talk', 'Talk'), ('invited', 'Invited Talk'), ('poster', 'Poster'), ('teaching', 'Teaching'), ('service', 'Service')], default='talk', max_length=20)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('url', models.URLField(blank=True, max_length=400)),
                ('slides_url', models.URLField(blank=True, max_length=400)),
                ('video_url', models.URLField(blank=True, max_length=400)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name']},
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first.'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show on the home page.'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(blank=True, to='portfolio.link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(help_text='Comma-separated. Your own name is auto-highlighted on the page.', max_length=500)),
                ('venue', models.CharField(help_text='e.g. "ICLR 2024", "NeurIPS Workshop".', max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(default=1, help_text='1-12, used only for ordering.')),
                ('kind', models.CharField(choices=[('conference', 'Conference'), ('journal', 'Journal'), ('workshop', 'Workshop'), ('preprint', 'Preprint'), ('thesis', 'Thesis')], default='conference', max_length=20)),
                ('abstract', models.TextField(blank=True, max_length=3000)),
                ('award', models.CharField(blank=True, help_text='Optional badge, e.g. "Oral", "Spotlight", "Best Paper".', max_length=120)),
                ('pdf_url', models.URLField(blank=True, max_length=400)),
                ('arxiv_url', models.URLField(blank=True, max_length=400)),
                ('code_url', models.URLField(blank=True, max_length=400)),
                ('project_url', models.URLField(blank=True, max_length=400)),
                ('video_url', models.URLField(blank=True, max_length=400)),
                ('slides_url', models.URLField(blank=True, max_length=400)),
                ('bibtex', models.TextField(blank=True, max_length=2000)),
                ('image', models.ImageField(blank=True, help_text='Optional teaser/figure thumbnail.', null=True, upload_to='publications/')),
                ('featured', models.BooleanField(default=False, help_text='Show on the home page.')),
                ('tags', models.ManyToManyField(blank=True, to='portfolio.tag')),
            ],
            options={
                'ordering': ['-year', '-month', '-id'],
            },
        ),
    ]
