# Generated by Django 6.0.6 on 2026-06-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_news_profile_researcharea_talk_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageLink',
        ),
    ]
