# Generated by Django 6.0.6 on 2026-06-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_delete_imagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='stage',
            field=models.CharField(blank=True, choices=[('training', 'Training'), ('test_time', 'Test-Time'), ('evaluation', 'Evaluation'), ('safety', 'Safety & Robustness')], default='', help_text='Where this paper sits in the LLM-agent lifecycle. Drives the interactive agent-lifecycle graphic on the home and research pages.', max_length=20),
        ),
    ]
