# Generated by Django 6.0.6 on 2026-06-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_publication_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL for this paper’s page. Auto-generated from the title if left blank.', max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='stage',
            field=models.CharField(blank=True, choices=[('data_generation', 'Data Generation'), ('training', 'Training'), ('test_time', 'Test-Time'), ('eval_safety', 'Evaluation & Safety')], default='', help_text='Where this paper sits in the LLM-agent lifecycle. Drives the interactive agent-lifecycle graphic on the home and research pages.', max_length=20),
        ),
    ]
