# Generated by Django 6.0.6 on 2026-06-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_publication_slug_alter_publication_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='project',
            name='links',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
        migrations.AddField(
            model_name='publication',
            name='tldr',
            field=models.CharField(blank=True, help_text='One-line TL;DR shown with featured publications on the home page.', max_length=300),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
