# Generated by Django 6.0.6 on 2026-07-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionBench',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ElectionBench', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='One-line description shown under the title.', max_length=300)),
                ('overview', models.TextField(blank=True, help_text='What the benchmark is and why (paragraphs).')),
                ('methodology', models.TextField(blank=True, help_text='How it works / experimental setup (paragraphs).')),
                ('status', models.CharField(blank=True, help_text='e.g. "Running — 42/100 scenarios". Also settable via the ingest API.', max_length=160)),
                ('results', models.JSONField(blank=True, default=dict, help_text='Streamed from the sim: {"columns": [...], "rows": [[...]], "note": "..."}.')),
                ('results_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ElectionBench',
                'verbose_name_plural': 'ElectionBench',
            },
        ),
    ]
