# Generated by Django 6.0.6 on 2026-07-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_electionbench'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=200, unique=True)),
                ('model_a', models.CharField(max_length=80)),
                ('model_b', models.CharField(max_length=80)),
                ('seed', models.IntegerField(default=0)),
                ('game_idx', models.IntegerField(default=0)),
                ('winner_model', models.CharField(blank=True, max_length=80)),
                ('popular_margin', models.FloatField(blank=True, null=True)),
                ('states_a', models.IntegerField(default=0)),
                ('states_b', models.IntegerField(default=0)),
                ('turnout', models.FloatField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['model_a', 'model_b', 'seed', 'game_idx'],
                'indexes': [models.Index(fields=['model_a', 'model_b'], name='portfolio_g_model_a_1548bb_idx')],
            },
        ),
    ]
