# Generated by Django 6.0.6 on 2026-07-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='detail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
