# Generated by Django 6.0.6 on 2026-07-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_game_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='raw_log',
            field=models.TextField(blank=True),
        ),
    ]
