# Generated by Django 6.0.6 on 2026-07-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_game_raw_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='body',
            field=models.TextField(blank=True, help_text='Optional long-form HTML for this paper’s page — method, figures, results. Rendered as-is below the abstract.'),
        ),
    ]
